### ISSUE TITLE
a;lerj;laksdvlnzxldrl;kqwejrlkawe

### ISSUE THREAD

**Issue by Heinrich-XIAO** [tweetoruser/Tweetify#1]
The How many communities to list?: (Max. 5) has a max of five? (I know that's crazy) but it has a default of 10. Does this have any user testting?

**Comment by tweetoruser** [comment]
Yes. There are five communities which is why it says max 5. When you add a community, that number goes up. I don't really see this as an issue so idk why you made this issue request.

**Comment by Heinrich-XIAO** [comment]
I added a community and it still says max 5.

**Comment by Heinrich-XIAO** [comment]
Also, merge my prs.

**Comment by tweetoruser** [comment]
Anyway I will be closing this issue since it's not really a major issue. When there are more than 10 communities then this won't really be a problem

**Comment by tweetoruser** [comment]
> I added a community and it still says max 5.

That's because I deleted someone else's community community. It's just a coincidence that I deleted a community right when you made a new one.

**Comment by tweetoruser** [comment]
> It is a major isue.

Not really
