### ISSUE TITLE
Community request

### ISSUE THREAD

**Issue by Heinrich-XIAO** [tweetoruser/Tweetify#3]
When doing searching for a community, /community/onemorethantheamountofcommunities will give you an internal server error.

**Comment by tweetoruser** [comment]
It says nonetype object is not subscriptable. It's because the community ID you are requesting does not exist.
Thank you for spotting this issue, I will work on fixing it.

**Comment by Heinrich-XIAO** [comment]
There's already a pr for this.

**Comment by tweetoruser** [comment]
> There's already a pr for this.

which breaks the application lmao

**Comment by Heinrich-XIAO** [comment]
> > There's already a pr for this.
> 
> which breaks the application lmao

That's intentional

**Comment by tweetoruser** [comment]
> > > There's already a pr for this.
> > 
> > 
> > which breaks the application lmao
> 
> That's intentional

I know it's intentional and i know it was to break the application. If you're going to do shit like this then just don't make a pr in the first place

**Comment by tweetoruser** [comment]
i will work on fixing this in a few hours

**Comment by tweetoruser** [comment]
It should be fixed now. I've added an error message when someone requests a community that doesn't exist.
